from manim import *
import os

class PlayWikiMedia(Scene):
    def construct(self):
        # Sequentially display media sources
        img = ImageMobject(r'images/Uterus_0.jpg')
        self.add(img)
        self.wait(1)
        self.remove(img)
        img = ImageMobject(r'images/Uterus_1.jpg')
        self.add(img)
        self.wait(1)
        self.remove(img)
        img = ImageMobject(r'images/Uterus_2.jpg')
        self.add(img)
        self.wait(1)
        self.remove(img)
        img = ImageMobject(r'images/Uterus_3.jpg')
        self.add(img)
        self.wait(1)
        self.remove(img)
        img = ImageMobject(r'images/Uterus_4.png')
        self.add(img)
        self.wait(1)
        self.remove(img)
        img = ImageMobject(r'images/Uterus_5.png')
        self.add(img)
        self.wait(1)
        self.remove(img)
        img = ImageMobject(r'images/Uterus_6.png')
        self.add(img)
        self.wait(1)
        self.remove(img)
        img = ImageMobject(r'images/Uterus_7.png')
        self.add(img)
        self.wait(1)
        self.remove(img)
        img = ImageMobject(r'images/Uterus_8.png')
        self.add(img)
        self.wait(1)
        self.remove(img)
        img = ImageMobject(r'images/Uterus_9.png')
        self.add(img)
        self.wait(1)
        self.remove(img)
        img = ImageMobject(r'images/Uterus_10.png')
        self.add(img)
        self.wait(1)
        self.remove(img)